import os
import warnings

import yaml

warnings.warn(
    "scripts/generate_decommissioning_checklist.py is deprecated. Use `uiao` CLI instead.",
    DeprecationWarning,
    stacklevel=1,
)
def generate_checklist():
  input_file = 'data/perimeter_collapse.yml'
  output_file = 'exports/decommissioning_checklist.md'

  if not os.path.exists('exports'):
    os.makedirs('exports')

  with open(input_file) as f:
    data = yaml.safe_load(f)

  with open(output_file, 'w') as f:
    f.write("# UIAO Decommissioning & Cost-Savings Checklist\n\n")
    f.write(f"> **Mission Context:** {data['perimeter_collapse']['narrative']}\n\n")
    f.write("This list identifies legacy TIC 2.2 assets that must be decommissioned upon successful UIAO validation.\n\n")

    for item in data['perimeter_collapse']['transitions']:
      f.write(f"## [{item['category']}] Transition\n")
      f.write(f"- [ ] **RETIRE:** {item['legacy']}\n")
      f.write(f"- [ ] **VALIDATE:** {item['uiao']} is operational.\n")
      f.write(f"- [ ] **IMPACT VERIFIED:** {item['impact']}\n\n")

    f.write("---\n*Generated by UIAO Foreman Engine v1.0*")

  print(f"Checklist generated: {output_file}")

if __name__ == "__main__":
  generate_checklist()
