#!/usr/bin/env python3
"""Quarto Post-Render Script for UIAO Document Pipeline.

Moves Quarto output from _output/ to exports/quarto/ with canonical naming.
Organizes by format type for clean artifact structure.

This script runs AFTER quarto render completes.
"""

import shutil
from pathlib import Path

OUTPUT_DIR = Path("_output")
EXPORT_DIR = Path("exports/quarto")

FORMAT_DIRS = {
    ".docx": "docx",
    ".pptx": "pptx",
    ".pdf": "pdf",
    ".html": "html",
    ".md": "markdown",
}


def organize_exports():
    """Move rendered files from _output/ to exports/quarto/ organized by format."""
    if not OUTPUT_DIR.exists():
        print(f"[quarto-post-render] WARNING: {OUTPUT_DIR} does not exist. Nothing to organize.")
        return

    # Create format subdirectories
    for subdir in FORMAT_DIRS.values():
        (EXPORT_DIR / subdir).mkdir(parents=True, exist_ok=True)

    moved = 0
    for rendered_file in sorted(OUTPUT_DIR.rglob("*")):
        if rendered_file.is_dir():
            continue

        suffix = rendered_file.suffix.lower()
        if suffix in FORMAT_DIRS:
            target_dir = EXPORT_DIR / FORMAT_DIRS[suffix]
            target_file = target_dir / rendered_file.name
            shutil.copy2(rendered_file, target_file)
            print(f"[quarto-post-render] EXPORT: {rendered_file} -> {target_file}")
            moved += 1
        else:
            # Copy supporting files (images, CSS, etc.) to html directory
            target_dir = EXPORT_DIR / "html" / "_resources"
            target_dir.mkdir(parents=True, exist_ok=True)
            target_file = target_dir / rendered_file.name
            shutil.copy2(rendered_file, target_file)

    print(f"\n[quarto-post-render] Complete: {moved} documents exported to {EXPORT_DIR}")

    # Generate manifest
    generate_manifest()


def generate_manifest():
    """Generate a manifest file listing all exported documents."""
    manifest_path = EXPORT_DIR / "MANIFEST.md"
    lines = [
        "# UIAO Document Export Manifest",
        "",
        "Generated by Quarto post-render pipeline.",
        "",
    ]

    for _format_name, subdir in sorted(FORMAT_DIRS.items()):
        format_dir = EXPORT_DIR / subdir
        files = sorted(format_dir.rglob("*"))
        files = [f for f in files if f.is_file() and f.name != "MANIFEST.md"]
        if files:
            lines.append(f"## {subdir.upper()} ({len(files)} files)")
            lines.append("")
            for f in files:
                size_kb = f.stat().st_size / 1024
                lines.append(f"- `{f.name}` ({size_kb:.1f} KB)")
            lines.append("")

    manifest_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[quarto-post-render] MANIFEST: {manifest_path}")


if __name__ == "__main__":
    organize_exports()
