name: Generate Changelog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'docs: update CHANGELOG.md [skip ci]'
          preset: 'angular'
          output-file: 'CHANGELOG.md'
          skip-on-empty: 'true'
          skip-version-file: 'true'
          skip-commit: 'false'
